// import {
//   SET_ACTIVE_CONTACT_TAB,
//   UPDATE_WALLET_CONTACTS,
//   INITIALIZE_WALLET_CONTACTS,
//   SET_CONTACT_ADDRESS,
//   INITIALIZE_CONTACT_TOKENS,
//   SET_TEMPORARY_QR_ADDRESS
// } from "../actionTypes/ContactTypes";
