/**
 * Action Types for App Configuration & AppConfig Action Creator File
 */
export const DEBUG_MODE = 'DEBUG_MODE';
export const INITIALIZE_APP_TOKEN_SETUP = 'INITIALIZE_APP_TOKEN_SETUP';
export const INITIALIZE_NEW_APP_WALLET = 'INITIALIZE_NEW_APP_WALLET';
export const TEMP_WALLET_NAME = 'TEMP_WALLET_NAME';
export const SET_TEMPORARY_QR_ADDRESS = 'SET_TEMPORARY_QR_ADDRESS';
export const PACKAGE_TOKEN_DETAILS_FOR_TRANSACTION = 'PACKAGE_TOKEN_DETAILS_FOR_TRANSACTION';
