export const EXIT_SETUP_SCREEN = 'EXIT_SETUP_SCREEN';
export const INITIALIZE_APP_TOKEN_SETUP = 'INITIALIZE_APP_TOKEN_SETUP';
export const INITIALIZE_NEW_APP_WALLET = 'INITIALIZE_NEW_APP_WALLET';
export const TEMP_WALLET_NAME = 'TEMP_WALLET_NAME';
export const DEBUG_MODE = 'DEBUG_MODE';
export const SET_APP_PASSWORD = 'SET_APP_PASSWORD';
export const CONFIG_HOT_WALLET = 'CONFIG_HOT_WALLET';
