/**
 * Contact related action types
 */
export const SET_ACTIVE_CONTACT_TAB = 'SET_ACTIVE_CONTACT_TAB';
export const UPDATE_WALLET_CONTACTS = 'UPDATE_WALLET_CONTACTS';
export const SET_TEMP_CONTACT_NAME = 'SET_TEMP_CONTACT_NAME';
export const INITIALIZE_WALLET_CONTACTS = ' INITIALIZE_WALLET_CONTACTS';
export const SET_CONTACT_ETHEREUM_ADDRESS = 'SET_CONTACT_ETHEREUM_ADDRESS';
export const INITIALIZE_CONTACT_TOKENS = 'INITIALIZE_CONTACT_TOKENS';


