export const SET_ACTIVE_CONTACT_TAB = 'SET_ACTIVE_CONTACT_TAB';
export const UPDATE_WALLET_CONTACTS = 'UPDATE_WALLET_CONTACTS';
export const INITIALIZE_WALLET_CONTACTS = 'INITIALIZE_WALLET_CONTACT';
export const SET_CONTACT_ADDRESS = 'SET_CONTACT_ADDRESS';
export const INITIALIZE_CONTACT_TOKENS = 'INITIALIZE_CONTACT_TOKENS';
