fastlane_version '2.53.1'

setup_travis

platform :ios do
  before_all do
    version_number = get_version_number(xcodeproj: "./ios/weipay.xcodeproj", target: "WeiPay")
    build_number = get_build_number(xcodeproj: "./ios/weipay.xcodeproj")
    ENV["VERSION_NUMBER"] = version_number + "." + build_number
  end

  desc 'Slack notification for succesful build to TestFlight'
  lane :slack_testflight do
    slack(
      message: "A new build has been uploaded to TestFlight!",
      success: true,
      slack_url: ENV['SLACK_WEBHOOK'],
      attachment_properties: {
        fields: [
          {
             title: "Version number",
             value: ENV["VERSION_NUMBER"],
          },
        ]
      }
    )
  end

  desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
      # Create a temporary keychain to
      # store the certificates.
      create_keychain(
        name: ENV["MATCH_KEYCHAIN_NAME"],
        password: ENV["MATCH_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        add_to_search_list: true
      )
      
      match(app_identifier: ENV['MATCH_IDENTIFIER'], type: 'development', readonly: true, clone_branch_directly: true)
      match(app_identifier: ENV['MATCH_IDENTIFIER'], type: 'appstore', readonly: true, clone_branch_directly: true)
    end

  desc 'Build the iOS application.'
    private_lane :build do
      certificates
      gym(scheme: 'WeiPay', project: './ios/weipay.xcodeproj')
    end

  desc 'Ship to Testflight.'
    lane :beta do
      build
      pilot(username: ENV['MATCH_EMAIL'])
      slack_testflight
    end
end

platform :android do
  desc 'Slack notification for succesful build to Playstore'
  lane :slack_playstore do
    slack(
      message: "A new build has been uploaded to the PlayStore",
      success: true,
      slack_url: ENV['SLACK_WEBHOOK'],
      attachment_properties: {
        fields: [
          {
             title: "Build number",
             value: ENV["BUILD_NUMBER"],
          },
        ]
      }
    )
  end

 desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
    supply(track: 'beta', track_promote_to: 'beta')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    push_to_git_remote
    slack_playstore
  end
end
